name: CI Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run security checks
      run: safety check
    - name: Run linting
      run: cd demo && pylint demo store --rcfile=pylint.rc
    - name: Run all tests
      run: cd demo && python3 manage.py test
